//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZpisRokovnikService.DataLayer
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseDTOOfKORISNIKKorisnikDTOCAdBun5G", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZpisRokovnikService.DataLayer.KorisnikDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZpisRokovnikService.DataLayer.LoginDTO))]
    public partial class BaseDTOOfKORISNIKKorisnikDTOCAdBun5G : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "KorisnikDTO", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    public partial class KorisnikDTO : ZpisRokovnikService.DataLayer.BaseDTOOfKORISNIKKorisnikDTOCAdBun5G
    {

        private string KorisnickoImeField;

        private string LozinkaField;

        private string ZaposlenNaTijelimaField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KorisnickoIme
        {
            get
            {
                return this.KorisnickoImeField;
            }
            set
            {
                this.KorisnickoImeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lozinka
        {
            get
            {
                return this.LozinkaField;
            }
            set
            {
                this.LozinkaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZaposlenNaTijelima
        {
            get
            {
                return this.ZaposlenNaTijelimaField;
            }
            set
            {
                this.ZaposlenNaTijelimaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LoginDTO", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    public partial class LoginDTO : ZpisRokovnikService.DataLayer.BaseDTOOfKORISNIKKorisnikDTOCAdBun5G
    {

        private string TokenField;

        private bool isAuthenticatedField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAuthenticated
        {
            get
            {
                return this.isAuthenticatedField;
            }
            set
            {
                this.isAuthenticatedField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseDTOOfOSOBAOsobaDTOCAdBun5G", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZpisRokovnikService.DataLayer.OsobaDTO))]
    public partial class BaseDTOOfOSOBAOsobaDTOCAdBun5G : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OsobaDTO", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    public partial class OsobaDTO : ZpisRokovnikService.DataLayer.BaseDTOOfOSOBAOsobaDTOCAdBun5G
    {

        private string AdresaField;

        private System.DateTime DatumRodenjaField;

        private string ImeField;

        private string OIBField;

        private string PrezimeField;

        private long VrstaOsobeIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumRodenja
        {
            get
            {
                return this.DatumRodenjaField;
            }
            set
            {
                this.DatumRodenjaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime
        {
            get
            {
                return this.ImeField;
            }
            set
            {
                this.ImeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OIB
        {
            get
            {
                return this.OIBField;
            }
            set
            {
                this.OIBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime
        {
            get
            {
                return this.PrezimeField;
            }
            set
            {
                this.PrezimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VrstaOsobeId
        {
            get
            {
                return this.VrstaOsobeIdField;
            }
            set
            {
                this.VrstaOsobeIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseDTOOfBROJNOSTANJE_VIEWBrojcanoStanjeDTOfY6h9TEE", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFServiceWebRole1.DataLayer.BrojcanoStanjeDTO))]
    public partial class BaseDTOOfBROJNOSTANJE_VIEWBrojcanoStanjeDTOfY6h9TEE : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PredmetDTO", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    public partial class PredmetDTO : ZpisRokovnikService.DataLayer.BaseDTOOfPREDMETPredmetDTOCAdBun5G
    {

        private System.Nullable<System.DateTime> DatumOsnivanjaField;

        private string NazivPredmetaField;

        private string OznakaPredmetaField;

        private long RedniBrojField;

        private long UpisnikIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatumOsnivanja
        {
            get
            {
                return this.DatumOsnivanjaField;
            }
            set
            {
                this.DatumOsnivanjaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivPredmeta
        {
            get
            {
                return this.NazivPredmetaField;
            }
            set
            {
                this.NazivPredmetaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OznakaPredmeta
        {
            get
            {
                return this.OznakaPredmetaField;
            }
            set
            {
                this.OznakaPredmetaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RedniBroj
        {
            get
            {
                return this.RedniBrojField;
            }
            set
            {
                this.RedniBrojField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UpisnikId
        {
            get
            {
                return this.UpisnikIdField;
            }
            set
            {
                this.UpisnikIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseDTOOfPREDMETPredmetDTOCAdBun5G", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZpisRokovnikService.DataLayer.PredmetDTO))]
    public partial class BaseDTOOfPREDMETPredmetDTOCAdBun5G : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "KalendarDTO", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    public partial class KalendarDTO : ZpisRokovnikService.DataLayer.BaseDTOOfKALENDARKalendarDTOCAdBun5G
    {

        private long KorisnikIdField;

        private System.Nullable<System.DateTime> KrajField;

        private System.Nullable<System.DateTime> PocetakField;

        private long PredmetIdField;

        private System.Nullable<long> VrstaKalendaraIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long KorisnikId
        {
            get
            {
                return this.KorisnikIdField;
            }
            set
            {
                this.KorisnikIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Kraj
        {
            get
            {
                return this.KrajField;
            }
            set
            {
                this.KrajField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Pocetak
        {
            get
            {
                return this.PocetakField;
            }
            set
            {
                this.PocetakField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PredmetId
        {
            get
            {
                return this.PredmetIdField;
            }
            set
            {
                this.PredmetIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> VrstaKalendaraId
        {
            get
            {
                return this.VrstaKalendaraIdField;
            }
            set
            {
                this.VrstaKalendaraIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseDTOOfKALENDARKalendarDTOCAdBun5G", Namespace = "http://schemas.datacontract.org/2004/07/ZpisRokovnikService.DataLayer")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZpisRokovnikService.DataLayer.KalendarDTO))]
    public partial class BaseDTOOfKALENDARKalendarDTOCAdBun5G : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}
namespace WCFServiceWebRole1.DataLayer
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BrojcanoStanjeDTO", Namespace = "http://schemas.datacontract.org/2004/07/WCFServiceWebRole1.DataLayer")]
    public partial class BrojcanoStanjeDTO : ZpisRokovnikService.DataLayer.BaseDTOOfBROJNOSTANJE_VIEWBrojcanoStanjeDTOfY6h9TEE
    {

        private System.Nullable<long> BrojIstraznihZatvorenikaMuskiField;

        private System.Nullable<long> BrojIstraznihZatvorenikaZenskiField;

        private System.Nullable<long> BrojKaznjenikaMuskiField;

        private System.Nullable<long> BrojKaznjenikaZenskiField;

        private System.Nullable<long> BrojZatvorenikaMuskiField;

        private System.Nullable<long> BrojZatvorenikaZenskiField;

        private System.Nullable<long> NaIzlaskuMuskiField;

        private System.Nullable<long> NaIzlaskuZenskiField;

        private System.Nullable<long> NaPrekidMuskiField;

        private string NazivTijelaField;

        private System.Nullable<long> ProlazniMuskiField;

        private System.Nullable<long> ProlazniZenskiField;

        private long TijeloIdField;

        private System.Nullable<long> UBijeguMuskiField;

        private System.Nullable<long> UBijeguZenskiField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BrojIstraznihZatvorenikaMuski
        {
            get
            {
                return this.BrojIstraznihZatvorenikaMuskiField;
            }
            set
            {
                this.BrojIstraznihZatvorenikaMuskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BrojIstraznihZatvorenikaZenski
        {
            get
            {
                return this.BrojIstraznihZatvorenikaZenskiField;
            }
            set
            {
                this.BrojIstraznihZatvorenikaZenskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BrojKaznjenikaMuski
        {
            get
            {
                return this.BrojKaznjenikaMuskiField;
            }
            set
            {
                this.BrojKaznjenikaMuskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BrojKaznjenikaZenski
        {
            get
            {
                return this.BrojKaznjenikaZenskiField;
            }
            set
            {
                this.BrojKaznjenikaZenskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BrojZatvorenikaMuski
        {
            get
            {
                return this.BrojZatvorenikaMuskiField;
            }
            set
            {
                this.BrojZatvorenikaMuskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BrojZatvorenikaZenski
        {
            get
            {
                return this.BrojZatvorenikaZenskiField;
            }
            set
            {
                this.BrojZatvorenikaZenskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NaIzlaskuMuski
        {
            get
            {
                return this.NaIzlaskuMuskiField;
            }
            set
            {
                this.NaIzlaskuMuskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NaIzlaskuZenski
        {
            get
            {
                return this.NaIzlaskuZenskiField;
            }
            set
            {
                this.NaIzlaskuZenskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NaPrekidMuski
        {
            get
            {
                return this.NaPrekidMuskiField;
            }
            set
            {
                this.NaPrekidMuskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivTijela
        {
            get
            {
                return this.NazivTijelaField;
            }
            set
            {
                this.NazivTijelaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ProlazniMuski
        {
            get
            {
                return this.ProlazniMuskiField;
            }
            set
            {
                this.ProlazniMuskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ProlazniZenski
        {
            get
            {
                return this.ProlazniZenskiField;
            }
            set
            {
                this.ProlazniZenskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TijeloId
        {
            get
            {
                return this.TijeloIdField;
            }
            set
            {
                this.TijeloIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UBijeguMuski
        {
            get
            {
                return this.UBijeguMuskiField;
            }
            set
            {
                this.UBijeguMuskiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UBijeguZenski
        {
            get
            {
                return this.UBijeguZenskiField;
            }
            set
            {
                this.UBijeguZenskiField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IService1")]
public interface IService1
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/TestMethod", ReplyAction = "http://tempuri.org/IService1/TestMethodResponse")]
    string[] TestMethod();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/TestMethod", ReplyAction = "http://tempuri.org/IService1/TestMethodResponse")]
    System.Threading.Tasks.Task<string[]> TestMethodAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/LoginUser", ReplyAction = "http://tempuri.org/IService1/LoginUserResponse")]
    ZpisRokovnikService.DataLayer.LoginDTO LoginUser(string Username, string Password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/LoginUser", ReplyAction = "http://tempuri.org/IService1/LoginUserResponse")]
    System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.LoginDTO> LoginUserAsync(string Username, string Password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetKorisnikByUsername", ReplyAction = "http://tempuri.org/IService1/GetKorisnikByUsernameResponse")]
    ZpisRokovnikService.DataLayer.KorisnikDTO GetKorisnikByUsername(string Username, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetKorisnikByUsername", ReplyAction = "http://tempuri.org/IService1/GetKorisnikByUsernameResponse")]
    System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.KorisnikDTO> GetKorisnikByUsernameAsync(string Username, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/VratiPrijavljenoTijelo", ReplyAction = "http://tempuri.org/IService1/VratiPrijavljenoTijeloResponse")]
    ZpisRokovnikService.DataLayer.OsobaDTO VratiPrijavljenoTijelo(string nazivPrijavljenogTijela, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/VratiPrijavljenoTijelo", ReplyAction = "http://tempuri.org/IService1/VratiPrijavljenoTijeloResponse")]
    System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.OsobaDTO> VratiPrijavljenoTijeloAsync(string nazivPrijavljenogTijela, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/VratiPrijavljenuOsobu", ReplyAction = "http://tempuri.org/IService1/VratiPrijavljenuOsobuResponse")]
    ZpisRokovnikService.DataLayer.OsobaDTO VratiPrijavljenuOsobu(long id, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/VratiPrijavljenuOsobu", ReplyAction = "http://tempuri.org/IService1/VratiPrijavljenuOsobuResponse")]
    System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.OsobaDTO> VratiPrijavljenuOsobuAsync(long id, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/VratiBrojcanoStanje", ReplyAction = "http://tempuri.org/IService1/VratiBrojcanoStanjeResponse")]
    WCFServiceWebRole1.DataLayer.BrojcanoStanjeDTO[] VratiBrojcanoStanje(string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/VratiBrojcanoStanje", ReplyAction = "http://tempuri.org/IService1/VratiBrojcanoStanjeResponse")]
    System.Threading.Tasks.Task<WCFServiceWebRole1.DataLayer.BrojcanoStanjeDTO[]> VratiBrojcanoStanjeAsync(string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/PretraziPoImenuIPrezimenu", ReplyAction = "http://tempuri.org/IService1/PretraziPoImenuIPrezimenuResponse")]
    ZpisRokovnikService.DataLayer.OsobaDTO[] PretraziPoImenuIPrezimenu(string Ime, string Prezime, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/PretraziPoImenuIPrezimenu", ReplyAction = "http://tempuri.org/IService1/PretraziPoImenuIPrezimenuResponse")]
    System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.OsobaDTO[]> PretraziPoImenuIPrezimenuAsync(string Ime, string Prezime, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/PretraziPoOIBu", ReplyAction = "http://tempuri.org/IService1/PretraziPoOIBuResponse")]
    ZpisRokovnikService.DataLayer.OsobaDTO PretraziPoOIBu(string OIB, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/PretraziPoOIBu", ReplyAction = "http://tempuri.org/IService1/PretraziPoOIBuResponse")]
    System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.OsobaDTO> PretraziPoOIBuAsync(string OIB, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/DohvatiPredmeteNaKojojJeOsobaKaznjenik", ReplyAction = "http://tempuri.org/IService1/DohvatiPredmeteNaKojojJeOsobaKaznjenikResponse")]
    ZpisRokovnikService.DataLayer.PredmetDTO[] DohvatiPredmeteNaKojojJeOsobaKaznjenik(long OsobaId, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/DohvatiPredmeteNaKojojJeOsobaKaznjenik", ReplyAction = "http://tempuri.org/IService1/DohvatiPredmeteNaKojojJeOsobaKaznjenikResponse")]
    System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.PredmetDTO[]> DohvatiPredmeteNaKojojJeOsobaKaznjenikAsync(long OsobaId, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/DohvatiKalendarskeZapise", ReplyAction = "http://tempuri.org/IService1/DohvatiKalendarskeZapiseResponse")]
    ZpisRokovnikService.DataLayer.KalendarDTO[] DohvatiKalendarskeZapise(string[] VrsteKalendara, long tijeloId, string token);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/DohvatiKalendarskeZapise", ReplyAction = "http://tempuri.org/IService1/DohvatiKalendarskeZapiseResponse")]
    System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.KalendarDTO[]> DohvatiKalendarskeZapiseAsync(string[] VrsteKalendara, long tijeloId, string token);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{

    public Service1Client()
    {
    }

    public Service1Client(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public Service1Client(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public string[] TestMethod()
    {
        return base.Channel.TestMethod();
    }

    public System.Threading.Tasks.Task<string[]> TestMethodAsync()
    {
        return base.Channel.TestMethodAsync();
    }

    public ZpisRokovnikService.DataLayer.LoginDTO LoginUser(string Username, string Password)
    {
        return base.Channel.LoginUser(Username, Password);
    }

    public System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.LoginDTO> LoginUserAsync(string Username, string Password)
    {
        return base.Channel.LoginUserAsync(Username, Password);
    }

    public ZpisRokovnikService.DataLayer.KorisnikDTO GetKorisnikByUsername(string Username, string token)
    {
        return base.Channel.GetKorisnikByUsername(Username, token);
    }

    public System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.KorisnikDTO> GetKorisnikByUsernameAsync(string Username, string token)
    {
        return base.Channel.GetKorisnikByUsernameAsync(Username, token);
    }

    public ZpisRokovnikService.DataLayer.OsobaDTO VratiPrijavljenoTijelo(string nazivPrijavljenogTijela, string token)
    {
        return base.Channel.VratiPrijavljenoTijelo(nazivPrijavljenogTijela, token);
    }

    public System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.OsobaDTO> VratiPrijavljenoTijeloAsync(string nazivPrijavljenogTijela, string token)
    {
        return base.Channel.VratiPrijavljenoTijeloAsync(nazivPrijavljenogTijela, token);
    }

    public ZpisRokovnikService.DataLayer.OsobaDTO VratiPrijavljenuOsobu(long id, string token)
    {
        return base.Channel.VratiPrijavljenuOsobu(id, token);
    }

    public System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.OsobaDTO> VratiPrijavljenuOsobuAsync(long id, string token)
    {
        return base.Channel.VratiPrijavljenuOsobuAsync(id, token);
    }

    public WCFServiceWebRole1.DataLayer.BrojcanoStanjeDTO[] VratiBrojcanoStanje(string token)
    {
        return base.Channel.VratiBrojcanoStanje(token);
    }

    public System.Threading.Tasks.Task<WCFServiceWebRole1.DataLayer.BrojcanoStanjeDTO[]> VratiBrojcanoStanjeAsync(string token)
    {
        return base.Channel.VratiBrojcanoStanjeAsync(token);
    }

    public ZpisRokovnikService.DataLayer.OsobaDTO[] PretraziPoImenuIPrezimenu(string Ime, string Prezime, string token)
    {
        return base.Channel.PretraziPoImenuIPrezimenu(Ime, Prezime, token);
    }

    public System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.OsobaDTO[]> PretraziPoImenuIPrezimenuAsync(string Ime, string Prezime, string token)
    {
        return base.Channel.PretraziPoImenuIPrezimenuAsync(Ime, Prezime, token);
    }

    public ZpisRokovnikService.DataLayer.OsobaDTO PretraziPoOIBu(string OIB, string token)
    {
        return base.Channel.PretraziPoOIBu(OIB, token);
    }

    public System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.OsobaDTO> PretraziPoOIBuAsync(string OIB, string token)
    {
        return base.Channel.PretraziPoOIBuAsync(OIB, token);
    }

    public ZpisRokovnikService.DataLayer.PredmetDTO[] DohvatiPredmeteNaKojojJeOsobaKaznjenik(long OsobaId, string token)
    {
        return base.Channel.DohvatiPredmeteNaKojojJeOsobaKaznjenik(OsobaId, token);
    }

    public System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.PredmetDTO[]> DohvatiPredmeteNaKojojJeOsobaKaznjenikAsync(long OsobaId, string token)
    {
        return base.Channel.DohvatiPredmeteNaKojojJeOsobaKaznjenikAsync(OsobaId, token);
    }

    public ZpisRokovnikService.DataLayer.KalendarDTO[] DohvatiKalendarskeZapise(string[] VrsteKalendara, long tijeloId, string token)
    {
        return base.Channel.DohvatiKalendarskeZapise(VrsteKalendara, tijeloId, token);
    }

    public System.Threading.Tasks.Task<ZpisRokovnikService.DataLayer.KalendarDTO[]> DohvatiKalendarskeZapiseAsync(string[] VrsteKalendara, long tijeloId, string token)
    {
        return base.Channel.DohvatiKalendarskeZapiseAsync(VrsteKalendara, tijeloId, token);
    }
}
