// <auto-generated />
namespace ZPISdatabaseAzure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _13112018_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13112018_4));
        
        string IMigrationMetadata.Id
        {
            get { return "201811132026449_13112018_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
