// <auto-generated />
namespace ZPISdatabaseAzure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _021220185 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_021220185));
        
        string IMigrationMetadata.Id
        {
            get { return "201901022010149_02122018-5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
