// <auto-generated />
namespace ZPISdatabaseAzure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _021220181 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_021220181));
        
        string IMigrationMetadata.Id
        {
            get { return "201901021813327_02122018-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
